### ISSUE TITLE
Help to add cookie 

### ISSUE THREAD

**Issue by minhprovjp** [serv0id/skipera#1]
I've tried many times to import cookie and save the config.py but I still facing with the output SyntaxError: invalid decimal literal. Can you give me more detail about import cookie to config.py file please?
![image](https://github.com/serv0id/skipera/assets/78216350/64c93d76-c55d-4fa6-862b-5042b1f8bf71)

**Comment by serv0id** [comment]
Hey, thanks for letting me know!

You need to specify the cookies as a dict with KV valuepairs, just like the `headers` dict in `config_example.py`. An easier way to do this is:

* Login to your account on coursera, open up a course. 
* Open the Developer Tools (Ctrl + Shift + I)
* Locate any call to coursera's domain and right click, copy as curl.
![image](https://github.com/serv0id/skipera/assets/113516593/3f3e2799-9545-4781-a1a1-6260d692b8c8)
* Paste the data at https://curlconverter.com/ and copy the cookies dict
![image](https://github.com/serv0id/skipera/assets/113516593/8bd17d7f-715e-4d66-a880-1c78ef3ee535)
* Paste the dict into config.py

**Comment by minhprovjp** [comment]
Done, thank you for the script.

**Comment by Shivang139** [comment]
curl 'https://www.coursera.org/api/degreeLearnerMemberships.v1?q=byUser&userId=145878235' \
  -H 'authority: www.coursera.org' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9,en-IN;q=0.8' \
  -H 'cookie: usprivacy=1---; OneTrustWPCCPAGoogleOptOut=false; IR_gbd=coursera.org; __204u=6357106642-1679730475450; FPID=FPID2.2.CrVecsc2F0VAWLGYin87xS2WS0z3t8OjJDbeIENa2JM%3D.1664793547; _hjSessionUser_469298=eyJpZCI6IjFmOGIwMjNlLWY0YTgtNWYzNC1iOTk1LWU3MTMxN2RlNmMyYiIsImNyZWF0ZWQiOjE2ODcxNTkwNDgxNzEsImV4aXN0aW5nIjp0cnVlfQ==; _ga=GA1.1.501244152.1664793547; __204r=https%3A%2F%2Fwww.bing.com%2F; G_ENABLED_IDPS=google; G_AUTHUSER_H=0; _fbp=fb.1.1705422305764.1920346540; IR_PI=945b0aee-4307-11ed-b872-0113b190ca9f%7C1707046004636; _gcl_au=1.1.819031711.1708948524; FPLC=3ajyviJeR11KBP9zSWdsRsLtz6nGQZbQCSYVCY%2F9342AUGsrH1BJxcepPAGTYRFZqwFUVDNTXLk3ODllUItaaX5W%2F2zPjvXCVrhtdxERmuVH8r1L%2B7umFLRtxuyrpg%3D%3D; CSRF3-Token=1710493639.QpJSTLUXa0SK2uFU; CAUTH=c_maV4HLA1JtcLNJGvv-cZnNzOva6pmZD1zYUxL1dOrCyaJRo5s8ouWy6l8zTY8cAk0h9PHI4rIVBKc5FfQZJQ.gHc-ftb-lTVlvSJd5MnMmQ.CdTM-rBbWRVDcW9OaSIJ7Lt1oV54UA7z0ip2gYsDcikoNmd4u1Lik5JgsZwxFaQs7ybC2nq68p7Y3zAaifv35Xp2CmHV4w5ndr1D8ltzLgzo59q1fZhNXhwPMfDk0FPKcplIKclY5hHZGMIvnVshFX9yxyXS2SjzK9F-lDLACZZmXSucR5f9rrdO0GkDeliK6lc4aDsnKyFwmBwx-P-bqGnCubWTX-0rBQVIP-vRV4PXafajmyimOtooxbaakrb9-9i38_Wp0TayvJSfis5PNgXy-LD5He7tf4iH5hgbSvO_NThPIfYBTZqiSlVVLkYLHP8-x_ak6jm0n6AhXNoy5HTTV5PmNNAw0mlMvlTSYqsVFpwOjMRedL6wFdM4aqujFEX-QSKurmUBDJMXdrEJri73IqhSyPy0sItsc0vYLWezVT5tL7buXHZqpWLHQ6CoenFDgNVn6AfgjN7ZpVyxTg; profileconsent=eyIxNDU4NzgyMzUiOnsiY2NwYVJlcXVpcmVkIjpmYWxzZSwiZ2RwclJlcXVpcmVkIjpmYWxzZX19; __400v=99b6cd95-b51e-43b8-9b43-1c48819f3feb; _ga_ZCE2Q9YZ3F=GS1.1.1709629635.44.1.1709634646.54.0.0; IR_14726=1709634646606%7C0%7C1709634646606%7C%7C; OptanonConsent=isIABGlobal=false&datestamp=Tue+Mar+05+2024+16%3A00%3A48+GMT%2B0530+(India+Standard+Time)&version=202401.1.0&hosts=&landingPath=NotLandingPage&groups=C0001%3A1%2CC0004%3A1%2CC0002%3A1%2CC0003%3A1&AwaitingReconsent=false&geolocation=IN%3B&isGpcEnabled=0&browserGpcFlag=0; OptanonAlertBoxClosed=2024-03-05T10:30:48.598Z; _ga_7GZ59JSFWQ=GS1.1.1709629637.47.1.1709634648.0.0.0; _tq_id.TV-63455409-1.39ed=511f37ec221b6ae6.1664793550.0.1709634649..; _rdt_uuid=1700573475218.8b9423a0-9e52-40cb-abb5-cec44f22891c; _uetsid=c4863700dacf11eea9cff7f7a4d61a15|1eflc2m|2|fjt|0|1525; _uetvid=9c6cffe0430711ed8e48a9dd2d88c491|ynlo22|1709635798334|108|1|bat.bing.com/p/insights/c/x; __400vt=1709635981846' \
  -H 'dnt: 1' \
  -H 'referer: https://www.coursera.org/learn/dynamic-programming-greedy-algorithms/home/week/2' \
  -H 'sec-ch-ua: "Chromium";v="122", "Not(A:Brand";v="24", "Microsoft Edge";v="122"' \
  -H 'sec-ch-ua-mobile: ?1' \
  -H 'sec-ch-ua-platform: "Android"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Mobile Safari/537.36 Edg/122.0.0.0'
